[package]
name = "sheets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
divi = {path = "../../"}
serde_json = "1.0.111"

[workspace]
